FROM kasmweb/core-ubuntu-jammy:1.15.0-rolling as patches

COPY patches /patches
ENV PATCHES="/dockerstartup/vnc_startup.sh,/patches/vnc_startup.sh.patch"

USER root
RUN \
  for PATCH in $PATCHES; do \
    ORIG=$(echo $PATCH | cut -d, -f1) && \
    PATCH=$(echo $PATCH | cut -d, -f2) && \
    patch $ORIG $PATCH || exit 1; \
  done

FROM kasmweb/core-ubuntu-jammy:1.15.0-rolling as base

USER root

# Copy patched files
RUN rm -rf /dockerstartup
COPY --from=patches /dockerstartup/ /dockerstartup/

ENV RUN_LEGACY_VNC false

# Desktopus dependencies
RUN apt-get update -y && \
    apt-get install -y \
    x11vnc \
    tigervnc-viewer

# Create desktopus user
RUN \
  usermod -l desktopus kasm-user && \
  groupmod -n desktopus kasm-user && \
  mkdir -p /home/desktopus && \
  chown -R 1000:0 /home/desktopus

# Special permissions for root scripts
COPY src/dockerstartup/root /dockerstartup/root
RUN chown root /dockerstartup/root/ && \
  chmod 755 /dockerstartup/root/ && \
  for SCRIPT in /dockerstartup/root/*; do \
    chown root $SCRIPT && \
    chmod 700 $SCRIPT; \
    echo "desktopus ALL=(ALL) NOPASSWD: $SCRIPT" >> /etc/sudoers; \
  done

# Allow root to desktopus or set password
RUN \
  echo "desktopus ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers; \
  chown -R 1000:0 /home/desktopus

USER 1000

FROM base

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="{{ range .Modules }}{{ . }} \
                  {{ end }}"

## Copy install scripts
COPY ./modules $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/desktopus
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
